### ISSUE TITLE
Bro its not SQLite xddd

### ISSUE THREAD

**Issue by gumernus** [Bialu-Software/developer-blog#2]
@HyScript7 pls

**Comment by HyScript7** [comment]
I told you I'll write an abstraction layer when I get home from holidays.
We'll use the Sequelize ORM, so that might add to the total size of the package.
I will be commiting to another branch, most likely `dbdev` or `database` and I will open a PR when it's stable.

**Comment by gumernus** [comment]
> I told you I'll write an abstraction layer when I get home from holidays.
> We'll use the Sequelize ORM, so that might add to the total size of the package.
> I will be commiting to another branch, most likely `dbdev` or `database` and I will open a PR when it's stable.

Great
