### ISSUE TITLE
Cookie Secret should be enforced away from the default value

### ISSUE THREAD

**Issue by gumernus** [Bialu-Software/developer-blog#3]
If someone doesn't change the secret key in the [config file](https://github.com/Bialu-Software/openpress/blob/main/config.json), there is security risk. So i propose that in the backend there is automatic generator of random keys and it generates a new key on the startup. Or so that if the key is set to the default vaule as shown in the config file, the backend would not start and will request a change of the key.

**Comment by HyScript7** [comment]
We could generate a hash of some random numbers and dump them into the config file if the value is default.

**Comment by gumernus** [comment]
yep

**Comment by gumernus** [comment]
@HyScript7 i have added that feature but how will we commit when the secret key will change on every dev start? and wouldnt be the default. is there a way to do it with github actions or should we use something else instead?
![image](https://github.com/Bialu-Software/openpress/assets/70224036/3bf6ae09-8d38-47b8-8bbf-1c2c61bad7c2)

**Comment by gumernus** [comment]
if we change the key on every startup so there can be anything in the config file then the development would be uhh because you would need new token every time you make a change and that is um..

**Comment by gumernus** [comment]
@thesvec ist your now xd

**Comment by HyScript7** [comment]
> @HyScript7 i have added that feature but how will we commit when the secret key will change on every dev start? and wouldnt be the default. is there a way to do it with github actions or should we use something else instead? ![image](https://user-images.githubusercontent.com/70224036/265050193-3bf6ae09-8d38-47b8-8bbf-1c2c61bad7c2.png)

The secret key really doesn't matter if it changes, since it's only used for cookie signing. If the server reboots, everyone will just login again. No problem.

**Edit:** Also I am not sure what you mean by "How will we commit"

**Comment by gumernus** [comment]
>  Also I am not sure what you mean by "How will we commit"

well if it was in the config.json then we would leak our keys. i think that the env will be the best option

**Comment by HyScript7** [comment]
> > Also I am not sure what you mean by "How will we commit"
> 
> well if it was in the config.json then we would leak our keys. i think that the env will be the best option

If you're talking about **the app writing a new default token on startup**, we can make disable it during testing. Make an environment flag called is_test_env, and if it's true, the script won't write the session secret into the config file. Also it's not that hard to just not stage the config file when committing.

**Comment by gumernus** [comment]
Well the env would be the best because it wouldn't be in config.json so github would be okay. And the program will just check if the env is set or not and if not it will make one. This way when you first start it up there will be no env and it will create on. If you then restart for some reason, the env will still be there so it would not need a new one = users don't have to login everytime the app is restarted.
