### ISSUE TITLE
Style bug

### ISSUE THREAD

**Issue by gumernus** [Bialu-Software/developer-blog#9]
![IMG_3917](https://github.com/Bialu-Software/openpress/assets/70224036/001399ad-b103-469a-964b-df257a720917)
Need to fix this so it uses the right colors and stuff

**Comment by HyScript7** [comment]
Also the language on the buttons is inconsistent. Replace "Nejstarší" with "Oldest" and "Nejmladší" with "Newest".

**Comment by gumernus** [comment]
Everytihng solved
